"use strict";
angular.module('components.directive', [
    'util.trsTDCheckModule',
    'util.dragdrop',
    'util.trsthumb',
    'util.trsScrollFixModule',
    'util.trsRadio',
    'util.trsSingleRadio',
    'util.trsSingleSelection',
    'util.trsEchartsModule',
    'util.trsWordNum',
    'util.JsonArrayToString',
    'util.httpService',
    "util.checkbox",
    "util.trsBigFaceModule",
    "util.trsLoginUserModule",
    "util.trsLeftMenu",
    'util.trsSliderModule',
    'util.trsDrag',
    "util.trslistIcon",
    "util.trsViewOriginalPic",
    "util.trsFinishRepeatModule",
    "trsPagenationConfigLeftModule",
    "trsPagenationConfigRightModule",
    "trsMasUploadDirective",
    'webIMModule',
    'trsPasswordStrongModule',
    /*  'trsScrollbar',*/
    'trsTimeSelectModule',
    'trsContentEditableModule',
    'editingCenter.imgUploadChg',
    'trsPasteModule',
    'util.trsScrollPicturesModule',
    'util.trsWeChatEditorModule',
    'editingCenter.imgUploadChgWeibo',
    'trsThumbScrollModule'//新增缩略图滚动
]);
